# Notebooks

In [1]:
2 + 2
print("hallo", 2 + 2)

hallo 4



## Überschrift
### kleinere ...

- Listen 
- mit 
- Strichen


* Listen
* mit
* Asterisk


1. Eins
2. Zwei
3. Dreißig


### Markdown-Docs:

- [adam-p/Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) (von Naomi)

# Numpy

Wieviel Erfahrung habt ihr mit Numpy (Modul)?

In [2]:
import numpy as np

In [3]:
print([1, 2, 3, 4]) # python list
print((1, 2, 3, 4)) # tuple

[1, 2, 3, 4]
(1, 2, 3, 4)


In [4]:
a = np.array([1, 2, 34, 5, 9])

## Array Operationen

In [5]:
print(a)
print(a + 1)
print(a * 2)
print(a > 4)

[ 1  2 34  5  9]
[ 2  3 35  6 10]
[ 2  4 68 10 18]
[False False  True  True  True]


Im Gegensatz dazu Listen:

In [6]:
[1, 2, 3] + [1]

[1, 2, 3, 1]

## Multidimensionale Arrays

In [7]:
b = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] )

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Auf Array-Elemente zugreifen

In [8]:
print(a)
print(a[3])

print()

print(b, "\n")
print(b[1], "\n")
print(b[1][0], "\n")

# 0 --> 1. Element
# 1 --> 2. Element

print(b[1, 0], "\n")

[ 1  2 34  5  9]
5

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5 6] 

4 

4 



In [9]:
print(a)
print(a[1:4]) # [1 - 4) --> inklusive 1; exklusive 4
print(a[:4])
print(a[1:])
print(a[:])

print()

print(b, "\n")
print(b[1:3], "\n")
print(b[1, 1:3], "\n")
print(b[1:3, 1], "\n")
print(b[:, 1], "\n")

[ 1  2 34  5  9]
[ 2 34  5]
[ 1  2 34  5]
[ 2 34  5  9]
[ 1  2 34  5  9]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[5 6] 

[5 8] 

[2 5 8] 



In [10]:
# 'Tab' --> Auto-completion
# 'Shift-Tab' --> Dokumentation

## Arrays erstellen

In [11]:
print(np.zeros(10))

print(np.shape(a))
print(np.shape(b))

print(np.zeros(np.shape(b)))

np.ones((3, 9, 3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(5,)
(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
print(np.linspace(2, 15), "\n")
print(np.linspace(2, 15, num=14), "\n")

[ 2.          2.26530612  2.53061224  2.79591837  3.06122449  3.32653061
  3.59183673  3.85714286  4.12244898  4.3877551   4.65306122  4.91836735
  5.18367347  5.44897959  5.71428571  5.97959184  6.24489796  6.51020408
  6.7755102   7.04081633  7.30612245  7.57142857  7.83673469  8.10204082
  8.36734694  8.63265306  8.89795918  9.16326531  9.42857143  9.69387755
  9.95918367 10.2244898  10.48979592 10.75510204 11.02040816 11.28571429
 11.55102041 11.81632653 12.08163265 12.34693878 12.6122449  12.87755102
 13.14285714 13.40816327 13.67346939 13.93877551 14.20408163 14.46938776
 14.73469388 15.        ] 

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.] 



In [13]:
np.arange(2, 16, 2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [14]:
print(b, "\n")
print(np.arange(1, 10), "\n")

print(np.reshape(np.arange(1, 10), (3, 3)), "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [15]:
print(np.random.rand(10))
print(np.random.randint(44, 100, 200))

[0.10519612 0.90678545 0.04598414 0.1100654  0.29280597 0.46425254
 0.76285282 0.19411068 0.7565273  0.75379149]
[58 85 46 80 59 56 92 53 51 60 80 45 96 82 48 45 72 80 86 82 80 83 46 50
 47 90 72 48 98 70 55 72 77 53 50 52 61 66 52 73 72 52 77 95 52 76 72 88
 89 55 88 54 60 48 56 44 73 98 61 92 58 79 92 99 65 56 60 56 93 48 63 59
 70 46 70 76 44 62 61 61 82 46 57 59 85 96 78 62 65 64 88 76 50 45 72 64
 81 45 64 88 86 96 83 67 62 75 99 47 74 83 76 71 95 46 72 96 73 44 54 99
 98 80 53 85 74 71 89 71 78 73 76 98 52 72 76 57 59 82 98 83 70 76 94 77
 54 91 52 60 96 45 60 92 55 87 73 66 55 93 84 71 49 60 88 85 89 65 59 78
 64 81 57 93 56 99 51 89 46 69 92 79 87 98 61 88 91 55 45 84 68 51 94 59
 79 49 45 82 87 57 66 89]


## Pi

In [16]:
np.pi

3.141592653589793

# Kurze Audio Demo

In [17]:
import IPython.display as ipd

x = np.random.rand(44100 * 3)

ipd.Audio(x, rate=44100)